---

- name: Apply grml zsh config
  get_url: url=https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc dest=~/.zshrc

- name: Create zsh config dir
  file: path=~/.zshrc.d/ state=directory

- name: Configure shell aspects
  template: src=templates/{{ item }}.j2 dest=~/.zshrc.d/{{ item }}
  with_items:
    - aliases
    - env
    - localbin

- name: Include zsh config dir
  copy: src=files/zshrc.local dest=~/.zshrc.local

- name: Detect shell path
  shell: which zsh
  register: shell_bin
  check_mode: no
  changed_when: false

- name: Set zsh as default login shell
  user: name={{ ansible_user }} shell={{ shell_bin.stdout }}
  become: True
