---

- hosts: macos
  roles:
    - { role: geerlingguy.homebrew, tags: ['brew', 'packages'] }
    - { role: geerlingguy.mas, tags: ['mas', 'packages'] }
    - { role: macos-system, tags: ['system'] }
    - { role: terminal, tags: ['terminal'] }
