---

- name: Apply macOS system defaults - {{ domain }}
  osx_defaults:
    domain: "{{ domain }}"
    key: "{{ key }}"
    value: "{{ item[key] }}"
    type: "{{ item.type | default('string' if item[key] is string else 'bool') }}"
    state: present
  vars:
    key: "{{ (item|list)[0] }}"
  with_list: "{{ defaults_domains[domain] }}"
