---

- name: Apply macOS system defaults - {{ domain }}
  osx_defaults:
    domain: "{{ domain }}"
    key: "{{ key }}"
    value: "{{ value }}"
    type: "{{ item.type | default('string' if value is string else 'bool') }}"
    state: present
  vars:
    key: "{{ item.key|default((item|list)[0]) }}"
    value: "{{ item.value|default(item[key]) }}"
  with_list: "{{ defaults_domains[domain] }}"
