---

defaults_domains:
  com.apple.finder:
    - AppleShowAllFiles: true
    - CreateDesktop: false
    - FXPreferredViewStyle: clmv
    - NewWindowTarget: PfHm
    - NewWindowTargetPath: "file://{{ '~/' | expanduser }}"
    - ShowPathbar: true
    - ShowPreviewPane: false
    - ShowRecentTags: false
    - ShowSidebar: true
    - ShowStatusBar: true
    - ShowTabView: false
    - SidebarDevicesSectionDisclosedState: true
    - SidebarPlacesSectionDisclosedState: true
    - SidebarSharedSectionDisclosedState: true
    - QLEnableTextSelection: true
  com.apple.dock:
    - key: tilesize
      value: 40
      type: float
    - mru-spaces: false
    - workspaces-auto-swoosh: true
    - mcx-disabled: true
  com.apple.screensaver:
    - askForPassword: true
    - askForPasswordDelay: 0
      type: float
  com.apple.screencapture:
    - location: "{{ '~/Pictures/Screenshots' | expanduser }}"
  com.apple.ActivityMonitor:
    - ShowCategory: 100
      type: int
  com.apple.menuextra.battery:
    - ShowPercent: "YES"
  com.apple.menuextra.clock:
    - DateFormat: "d. MMM  HH:mm:ss"
  com.apple.Siri:
    - StatusMenuVisible: false
  com.apple.SoftwareUpdate:
    - AutomaticDownload: True
    - ConfigDataInstall: True
    - CriticalUpdateInstall: True
    - ScheduleFrequency: 1
      type: int
  com.apple.commerce:
    - AutoUpdate: True
  com.if.Amphetamine:
    - "Show Dock Icon": 0
      type: int
  com.apple.TimeMachine:
    - DoNotOfferNewDisksForBackup: True
  com.apple.driver.AppleBluetoothMultitouch.trackpad:
    - TrackpadRightClick: True
  com.apple.driver.AppleBluetoothMultitouch.mouse:
    - MouseButtonMode: TwoButton
  NSGlobalDomain:
    - AppleShowAllExtensions: true
    - AppleInterfaceStyle: Dark
    - NSNavPanelExpandedStateForSaveMode: true
    - NSNavPanelExpandedStateForSaveMode2: true
    - key: AppleKeyboardUIMode
      value: 3
      type: int

energy_settings:
  battery:
    lidwake: 1
    autopoweroff: 1
    autopoweroffdelay: 28800
    standbydelay: 10800
    standby: 1
    ttyskeepawake: 1
    hibernatemode: 3
    powernap: 0
    gpuswitch: 2
    displaysleep: 3
    sleep: 1
    acwake: 0
    halfdim: 1
    lessbright: 0
    disksleep: 10
    sms: 0
  charger:
    lidwake: 1
    autopoweroff: 1
    autopoweroffdelay: 28800
    standbydelay: 10800
    standby: 1
    ttyskeepawake: 1
    hibernatemode: 3
    powernap: 1
    gpuswitch: 2
    displaysleep: 60
    womp: 1
    networkoversleep: 0
    sleep: 60
    acwake: 0
    halfdim: 1
    disksleep: 10
    sms: 0
